const rows = `
sinai-icon|Christ Pantocrator, Sinai|Col 1:15|6th century|icon|The ancient Sinai panel presents Christ frontally with a Gospel book and a gesture of blessing.|A Byzantine devotional image, not an eyewitness likeness of Jesus or a literal illustration of every phrase in Colossians.
michelangelo-pieta|Pietà, St. Peter's Basilica|Jhn 19:38|1498–1499|sculpture|Michelangelo's marble group shows Mary holding the body of Jesus; the selected image photographs the actual sculpture.|The Pietà is a later devotional subject. The Gospels do not explicitly describe Mary holding Jesus in this pose.
sistine-ceiling|Sistine Chapel ceiling: complete overview|Gen 1|1508–1512|fresco|The complete ceiling overview places the Genesis scenes within Michelangelo's larger arrangement of figures and architectural illusion.|This is a Renaissance theological composition, not a literal diagram of creation. Individual scenes are also catalogued separately.
kells-chi-rho|Book of Kells: Chi Rho page|Mat 1:18|Around 800 CE|manuscript|The decorated Chi Rho initials introduce the account of Christ's birth in Matthew.|An Insular manuscript page produced centuries after the Gospel; the ornament is not part of the original text.
lindisfarne-matthew|Lindisfarne Gospels: Matthew opening|Mat 1|Early 8th century|manuscript|The opening page of Matthew combines decorated letters with the beginning of the Gospel's genealogy.|A medieval witness to the Gospel text, not an autograph manuscript.
alexandrinus|Codex Alexandrinus: end of Luke|Luk 24|5th century|manuscript|Folio 41v preserves the conclusion of Luke with a decorative ending.|The selected leaf is from Luke, not John. Its text and ornament belong to this later manuscript witness.
leningrad-codex|Leningrad Codex: Genesis 14–15|Gen 14|1008–1009 CE|manuscript|The selected page contains Genesis 14:12–15:13 in the Hebrew Bible.|A medieval manuscript witness; it is not a page containing Genesis 1 or a patriarchal-era document.
aleppo-codex|Aleppo Codex: historical photograph of the commandments|Deu 5|10th-century codex; photograph published in 1909|manuscript|A historical photograph preserves a now-missing page containing the commandments in Deuteronomy.|This is a photographic witness to a lost leaf, not a current photograph of an intact page or an illustration of Deuteronomy 6.
great-isaiah|Great Isaiah Scroll: photographic detail|Isa 53|Around the 2nd century BCE|manuscript|A photographic detail of the Hebrew Isaiah scroll helps readers examine an ancient textual witness.|This is a reproduction of a scroll surface, not a modern translation; individual readings require textual study.
nash-papyrus|Nash Papyrus|Exo 20|2nd–1st century BCE|manuscript|Joined papyrus fragments preserve material related to the commandments and the Shema.|The fragment is not a complete Torah scroll and combines material rather than reproducing an entire biblical book.
p52|Rylands Papyrus P52: John 18 fragment|Jhn 18:31|2nd century CE in the source record; dating is approximate|manuscript|A small Greek papyrus fragment preserves words from John 18.|Palaeographic dating is approximate; do not treat the fragment as the original authorial manuscript or claim an undisputed exact year.
p75|Papyrus P75: Luke 14|Luk 14:3|3rd century CE in the source record; dating is approximate|manuscript|The selected papyrus page contains Luke 14:3–14.|This page is not Luke 24. Manuscript dating and readings require scholarly interpretation.
p46|Papyrus P46: Pauline-letter bifolio|Rom 11:13|Around 200 CE|manuscript|This bifolio brings together portions of Romans 11, the end of Philippians and the beginning of Colossians.|The image contains several physical page surfaces; it is not a continuous page of Romans 1.
p45|Papyrus P45: Luke 13–14|Luk 13:29|Around 200–250 CE|manuscript|The selected leaf preserves portions of Luke 13:29–35 and 14:1–10.|It is a fragmentary early manuscript witness, not a complete Gospel or a leaf from Mark.
armenian-roslin|Gabriel: Armenian Gospel Annunciation leaf|Luk 1:26|1262|manuscript|An illuminated Armenian Gospel leaf presents Gabriel in the Annunciation tradition.|This is one part of a manuscript image cycle, not an eyewitness picture of Gabriel's appearance.
rabbula-ascension|Rabbula Gospels: Ascension illumination|Act 1:9|6th century|manuscript|A Syriac Gospel-book illumination presents the Ascension in a developed visual tradition.|The arrangement and symbolic details are later interpretation, not additional details supplied by Acts.
syriac-gospel|Rabbula Gospels: canon table with evangelists|Luk 1|6th century|manuscript|A decorated canon table helps show how readers compared corresponding Gospel passages.|This is a reference apparatus, not the text of Luke 1 or a first-century structure.
vienna-genesis|Vienna Genesis: Rebecca at the well|Gen 24|6th century|manuscript|The manuscript illustration places Rebecca's meeting at the well within a late-antique visual setting.|The architecture, dress and additional figures reflect the illustrator's interpretation.
rossano-gospels|Rossano Gospels: Good Samaritan|Luk 10:30|6th century|manuscript|An illuminated Gospel page presents the parable of the Good Samaritan.|The pictured figures and symbolic interpretation go beyond the words of the parable.
utrecht-psalter|Utrecht Psalter: illustrated manuscript page|Psa 1|9th century|manuscript|A page from an illustrated Latin Psalter demonstrates a medieval way of reading poetry through line drawing.|The Psalms association is collection-level context; the selected folio is not claimed to contain Psalm 1 or Psalm 23.
codex-aureus|Codex Aureus: the rich man and Lazarus|Luk 16:19|Around 1035–1040|manuscript|An illuminated page develops scenes from the parable of the rich man and Lazarus.|The medieval visual details are an interpretation, not a diagram of the afterlife endorsed by the reader.
rublev-trinity|Trinity icon|Gen 18|Early 15th century|icon|Rublev's icon draws on the three visitors received by Abraham to express a later Trinitarian interpretation.|A theological icon, not a literal eyewitness reconstruction of the Genesis encounter.
vladimir-icon|Theotokos of Vladimir|Luk 2|12th-century icon tradition|icon|The icon presents an intimate devotional image of Mary and the Christ child.|Its pose and theological symbolism are later tradition, not a named moment in Luke 2.
sinai-ladder|Ladder of Divine Ascent icon|Mat 7:13|Medieval Byzantine icon|icon|Monks ascending a ladder illustrate the spiritual teaching associated with John Climacus.|The image illustrates a later monastic work, not a ladder described in Matthew's Gospel.
monreale-pantocrator|Christ Pantocrator, Monreale apse|Col 1:15|Late 12th century|mosaic|An expansive apse mosaic presents Christ above the church interior.|This medieval church image is a devotional interpretation, not an ancient portrait from Christ's lifetime.
cefalu-pantocrator|Christ Pantocrator, Cefalù apse|Jhn 1|12th century|mosaic|The gold-ground apse mosaic places the figure of Christ within a monumental church setting.|A medieval visual interpretation of Christ's identity, not a literal image of John's opening verses.
hagia-sophia-deesis|Hagia Sophia: Deësis mosaic|Heb 4:14|13th century|mosaic|A mosaic group presents Christ in a later intercessory and devotional tradition.|The composition reflects Byzantine theology and is not a scene narrated in Hebrews.
ravenna-shepherd|Good Shepherd mosaic, Galla Placidia|Jhn 10:11|5th century|mosaic|A shepherd figure among sheep offers an early Christian visual treatment of care and protection.|The association with John 10 is thematic rather than an eyewitness depiction.
san-vitale-abraham|San Vitale: Abraham's hospitality mosaic|Gen 18|6th century|mosaic|The lunette combines episodes associated with Abraham within a rich church decoration.|Multiple narrative and theological motifs are combined rather than presented as one historical instant.
san-vitale-melchizedek|San Vitale: Abel and Melchizedek mosaic|Heb 7|6th century|mosaic|The juxtaposition of Abel and Melchizedek develops a Christian typological reading of offerings.|The two figures belong to different Genesis narratives; the mosaic is a later theological comparison.
ravenna-magi|Sant'Apollinare Nuovo: Magi mosaic|Mat 2:11|6th century|mosaic|The visitors carrying gifts appear in a colorful procession with distinctive clothing.|Their number, names and clothing reflect later artistic tradition, not all details stated in Matthew.
chora-anastasis|Chora: Anastasis fresco|1Pe 3:18|Early 14th century|fresco|The fresco presents the Byzantine Anastasis or Harrowing of Hell tradition.|This is a later theological interpretation; the full scene is not narrated in 1 Peter.
ravenna-baptism|Neonian Baptistery: baptism mosaic|Mat 3:13|5th century|mosaic|A central baptism scene is set within a larger late-antique mosaic program.|The visual symbolism and surrounding figures are artistic interpretation of the Gospel subject.
garima-detail|Garima Gospels: illuminated canon table|Jhn 1|Late antiquity; 6th century in the source record|manuscript|An Ethiopian Gospel illumination demonstrates a distinctive tradition of decorated reference tables.|This is manuscript context, not a first-century Gospel autograph or a claim that this table contains John 1.
morgan-leaf|Morgan Picture Bible: David and Absalom|2Sa 18|Around 1250|manuscript|The selected leaf continues the story of David and his rebellious son Absalom.|It is not a David-and-Goliath leaf. Armor and settings follow a medieval European visual world.
vaticanus-leaf|Codex Vaticanus: Matthew 1–2 reproduction|Mat 2|4th-century manuscript; later reproduction|manuscript|The reproduced page contains Matthew 1:22–2:18.|The image is a reproduction of a manuscript leaf, not a photograph of Matthew writing the Gospel.
beth-alpha|Beth Alpha synagogue mosaic floor|Gen 22|6th century CE|mosaic|A synagogue floor places the binding of Isaac within a broader mosaic program.|This is later Jewish sacred art; the surrounding zodiac and other motifs are not part of the Genesis narrative.
madaba|Madaba mosaic map: Holy Land detail|Luk 19|6th century CE|mosaic|A surviving floor mosaic depicts places through the cartographic and religious outlook of late antiquity.|It is not a modern map or an exact reconstruction of Jerusalem in the first century.
sinai-transfiguration|Sinai monastery: Transfiguration mosaic|Mat 17|6th century CE|mosaic|The monastery apse mosaic gives a monumental late-antique interpretation of the Transfiguration.|The style and arrangement reflect church art produced centuries after the Gospel events.
toros-baptism|Armenian Gospels: baptism of Christ|Mat 3:13|1262|manuscript|A T'oros Roslin Gospel illumination presents the baptism of Christ.|Its pictorial details belong to the Armenian manuscript tradition, not to a literal reconstruction.
ethiopian-crucifixion|Ethiopian Gospels: Crucifixion leaf|Jhn 19:17|Around 1540|manuscript|An illuminated Ethiopian Gospel leaf presents the Crucifixion through a distinctive manuscript tradition.|This is a painted manuscript leaf, not a freestanding icon panel or eyewitness record.
ethiopian-diptych|Ethiopian diptych with sacred scenes|Luk 2|Late 17th–early 18th century|icon|A surviving paired panel presents devotional subjects from an originally larger painted ensemble.|One original panel is missing; the surviving work should not be described as a complete triptych.
georgian-gospels|Mokvi Gospels: John dictating to Prochorus|Jhn 1|1300; archival reproduction|manuscript|A Georgian manuscript miniature depicts John dictating in a later tradition of evangelist portraits.|Prochorus as John's scribe is a later tradition, not a detail stated in the Gospel itself.
`;
export const HERITAGE_REVIEW=Object.fromEntries(rows.trim().split('\n').map(line=>{
 const[id,title,reference,date,technique,description,caution]=line.split('|');
 const manuscript=technique==='manuscript';
 return [`heritage-${id}`,{title,reference,date,technique,description,caution,kind:manuscript?'manuscript':'artwork',collections:['heritage'],creator:'Artist or scribe unidentified',culture:'Sacred art and manuscript tradition',medium:manuscript?'Manuscript page or documented reproduction':`${technique[0].toUpperCase()+technique.slice(1)}, photographed`,relationship:manuscript?'textual-history':'thematic',passageNote:description+' '+caution}];
}));
Object.assign(HERITAGE_REVIEW['heritage-sinai-icon'],{creator:'Anonymous Byzantine artist',period:'Byzantine',holdingCollection:"Saint Catherine's Monastery, Sinai",medium:'Encaustic on wood, reproduced'});
Object.assign(HERITAGE_REVIEW['heritage-michelangelo-pieta'],{creator:'Michelangelo',period:'Renaissance',holdingCollection:"St. Peter's Basilica, Vatican",photographer:'Maksim Sokolov (maxergon.com)'});
Object.assign(HERITAGE_REVIEW['heritage-sistine-ceiling'],{creator:'Michelangelo',period:'Renaissance',holdingCollection:'Sistine Chapel, Vatican',photographer:'Antoine Taveneaux',workGroup:'michelangelo-sistine-ceiling',relationship:'depiction'});
Object.assign(HERITAGE_REVIEW['heritage-rublev-trinity'],{creator:'Andrei Rublev',period:'Byzantine / Russian icon tradition'});
for(const id of ['armenian-roslin','toros-baptism'])Object.assign(HERITAGE_REVIEW['heritage-'+id],{creator:"T'oros Roslin",culture:'Armenian',period:'Medieval Armenian'});
for(const id of ['syriac-gospel','utrecht-psalter','garima-detail'])HERITAGE_REVIEW['heritage-'+id].inline=false;
HERITAGE_REVIEW['heritage-rabbula-ascension'].workGroup='rabbula-gospels';HERITAGE_REVIEW['heritage-syriac-gospel'].workGroup='rabbula-gospels';
HERITAGE_REVIEW['heritage-ethiopian-crucifixion'].culture='Ethiopian';HERITAGE_REVIEW['heritage-ethiopian-diptych'].culture='Ethiopian';
