/** Editorial labels checked against each selected file and its object description.
 * Deliberately separate artifact date, maker and photographer. */
const rows = `
mesha-stele|Mesha Stele|2Ki 3|c. 850 BCE|The Moabite royal inscription presents Mesha's account of conflict with Israel.|A royal victory account has its own political viewpoint; it does not independently verify every detail of 2 Kings.
tel-dan|Tel Dan Stele fragments|2Ki 8|9th century BCE|Fragments of an Aramaic royal inscription provide context for the kingdoms around Israel and Judah.|The inscription is fragmentary; reconstructions and historical identifications require interpretation.
merneptah|Merneptah Victory Stele|Exo 1|Late 13th century BCE|An Egyptian royal victory monument records peoples and places in the Levant.|This is not an account of the Exodus and does not establish its date.
siloam-inscription|Siloam tunnel inscription|2Ki 20:20|Late 8th century BCE|The inscription describes the meeting of work parties cutting a water tunnel at Jerusalem.|Its engineering account is related historical context, not a complete account of Hezekiah's reign.
sennacherib-prism|Taylor Prism of Sennacherib|2Ki 18|Early 7th century BCE|An Assyrian royal prism describes campaigns including the invasion of Judah.|Read this imperial account beside, not as an interchangeable version of, the biblical narrative.
lachish-reliefs|Assyrian reliefs of the siege of Lachish|2Ki 18:14|7th century BCE; depicts the 701 BCE campaign|Carved siege scenes show soldiers, defensive works and captives in an Assyrian presentation of victory.|The relief is royal propaganda and artistic representation, not a neutral photograph of the battle.
cyrus-cylinder|Cyrus Cylinder|Ezr 1|6th century BCE|A Babylonian inscription presents Cyrus's kingship and restoration policies.|It does not name the Judean returnees or reproduce the decree in Ezra.
black-obelisk|Black Obelisk of Shalmaneser III|2Ki 9|9th century BCE|Tribute scenes and inscriptions illustrate how Assyria represented subordinate rulers and peoples.|Royal imagery and identifications must be read in the monument's own political context.
arad-ostracon|Arad ostracon 18|Jer 34|Late Iron Age|A written pottery fragment offers a tangible example of administration in ancient Judah.|It is not a letter written by Jeremiah or a record of the particular scene in Jeremiah 34.
hezekiah-seal|Bulla of Yehozarah, servant of Hezekiah|2Ki 20|8th century BCE|A seal impression naming a royal servant supplies context for Judahite court administration.|This is the servant's bulla, not Hezekiah's personal royal seal.
warning-inscription|Jerusalem Temple warning inscription|Act 21|Second Temple period|Greek lettering on the surviving warning stone illustrates regulated access within the Temple precinct.|An actual inscription does not mean this was the stone encountered by Paul.
magdala-stone|Magdala Stone|Mrk 1:21|1st century CE|A carved stone from the synagogue at Magdala preserves imagery associated with Jewish worship.|It is not a surviving furnishing from the Capernaum synagogue named in Mark.
galilee-boat|Ancient Galilee fishing boat|Luk 5|Around the 1st century CE|The conserved wooden hull helps convey the material scale of ancient lake travel and fishing.|It cannot be identified as a boat owned or used by Jesus or the disciples.
caiaphas-ossuary|Ossuary attributed to the Caiaphas family|Mat 26:57|1st century CE|A decorated limestone bone box illustrates burial practice and an important family-name inscription.|Its association with the high priest is an interpretation, not an eyewitness record of the trial.
erastus|Erastus pavement inscription at Corinth|Rom 16:23|Roman period; commonly assigned to the 1st century CE|A pavement inscription names a benefactor called Erastus.|Identifying this benefactor with the Erastus in Romans remains debated.
augustus-coin|Silver denarius of Augustus|Luk 2:1|13 BCE|An imperial portrait coin gives a material comparison for the ruler named in Luke.|This coin does not document the census or the circumstances of Jesus' birth.
tiberius-coin|Silver denarius of Tiberius|Mat 22:19|14–37 CE|A surviving denarius illustrates imperial portrait coinage used in the Roman world.|It is not the exact coin shown to Jesus; the type used in the Gospel episode is not certain.
tyrian-shekel|Tyrian silver coin from the Huseifa hoard|Mat 17:24|Late Hellenistic / early Roman period|A museum example of Tyrian silver coinage supplies context for regional currency and payments.|Do not identify this individual coin as a Temple-tax payment recorded in Matthew.
widows-mite|Bronze prutah of Alexander Jannaeus|Mrk 12:42|103–76 BCE|A small bronze coin helps visualize low-denomination regional money.|It predates the Gospel episode and is not one of the widow's actual coins.
pilate-coin|Bronze prutah issued under Pontius Pilate|Luk 3:1|29–30 CE|A provincial bronze coin supplies material context for Pilate's administration.|The coin does not depict or record the trial of Jesus.
felix-coin|Coin issued under Antonius Felix|Act 24|54 CE|A provincial coin supplies context for the Roman official named in Acts.|It is not evidence for the details of Paul's hearing.
agrippa-coin|Bronze coin attributed to Herod Agrippa|Act 12|Roman period|A bronze prutah provides context for Herodian coinage.|The selected file's attribution is retained without using the image alone to resolve every dynastic identification.
revolt-shekel|First Jewish Revolt bronze prutah|Luk 21|67–68 CE|A bronze coin carrying revolt-era wording shows the material expression of the later conflict.|This is bronze, not a silver shekel, and was struck decades after Jesus' ministry.
ishtar-lion|Glazed-brick lion from Babylon|Dan 1|Neo-Babylonian period|Colored glazed bricks show how monumental architecture in Babylon was decorated.|This is cultural context, not the lion from a biblical episode.
susa-frieze|Archer frieze from the palace at Susa|Est 1|c. 510 BCE|Glazed bricks arranged as archers illustrate Achaemenid royal decoration.|The palace decoration cannot identify the people or precise room in Esther's narrative.
lamassu|Assyrian winged human-headed bull|Isa 37|Neo-Assyrian period|A monumental protective figure conveys the scale and symbolism of Assyrian palace architecture.|It belongs to Assyrian visual religion and is not a depiction of a biblical angel.
sargon-relief|Assyrian hero mastering a lion, Louvre AO 19861|Isa 20:1|Late 8th century BCE|A palace relief from Khorsabad presents a heroic figure with a lion.|The figure is not a securely identified portrait of Sargon II; the association is with the imperial setting.
behistun|Behistun royal relief and inscription|Ezr 6|Late 6th–early 5th century BCE|A Persian royal monument combines figures and multilingual writing.|It supplies imperial context, not a record of rebuilding Jerusalem's Temple.
hammurabi|Stele of Hammurabi|Exo 21|18th century BCE|A Mesopotamian law monument offers a comparison for the public presentation of ancient law.|It is a different legal collection from another society and century, not a copy of Exodus.
baal-stele|Baal with Thunderbolt stele|1Ki 18|Late Bronze Age|An Ugaritic religious image helps readers recognize an ancient visual tradition associated with Baal.|It is much earlier than Elijah and is not an object used in the Mount Carmel episode.
flood-tablet|Mesopotamian Flood Tablet|Gen 6|7th century BCE tablet|A cuneiform tablet preserves part of a Mesopotamian flood narrative.|It is not a manuscript of Genesis; similarities and differences should both be retained.
roman-lamp|Roman terracotta oil lamp|Mat 25:1|1st century CE|A small clay lamp makes the Gospel imagery of lamps and oil more concrete.|This is a period comparison, not an object owned by one of the figures in the parable.
herodian-lamp|Hellenistic and Herodian oil lamps|Mat 5:15|Hellenistic / early Roman periods|A museum group shows variations in small lamps from neighboring periods.|The objects do not all have one date, and none can be assigned to a particular Gospel household.
bronze-lamp|Roman bronze oil lamp|Luk 15:8|Roman period|A metal lamp offers a comparison for lighting an interior while searching.|It is not the lamp in Jesus' parable, and households used different forms and materials.
amphora|Roman glass amphora|Mrk 7:4|1st century BCE–1st century CE|A small glass vessel illustrates one ancient amphora-shaped form.|This is not a large ceramic cargo amphora; the connection is to vessels, not ship freight.
unguentarium|Greek glass unguentarium|Mrk 14|Late 3rd–early 2nd century BCE|A slender glass perfume container illustrates the storage of aromatic substances.|This earlier Greek glass object is neither alabaster nor the vessel named in Mark.
alabaster-jar|Perfume vessel from Tutankhamun's tomb|Luk 7:37|14th century BCE|An elaborate Egyptian stone vessel offers a material comparison for containers holding perfume.|It predates the Gospels by more than a millennium and is not the woman's vessel in Luke.
bronze-mirror|Etruscan bronze mirror|1Co 13:12|3rd–2nd century BCE|A polished-metal mirror offers a comparison for reflection before modern glass mirrors.|This Etruscan object predates Paul and is not a mirror from his household.
slingstones|Sling stones and a spearhead from Lachish|1Sa 17|Iron Age|Surviving projectiles illustrate simple weapons alongside the account of a sling.|These are not David's stones; the displayed objects come from a different historical context.
arrowheads|Arrowheads from the siege of Lachish|2Ki 18:14|Associated with the 701 BCE campaign|Excavated iron arrowheads give material context to siege warfare.|They document the site's violence, not the individual actions of every figure in the biblical account.
roman-gladius|Roman sword from Germany|Eph 6:17|Roman period|A short Roman sword helps visualize the military comparison in Ephesians.|Its findspot is outside Judea; it is not Paul's or a named soldier's weapon.
roman-shield|Painted shield from Dura-Europos|Eph 6:16|Mid-3rd century CE|A conserved wooden shield preserves painted military decoration.|It is later than Ephesians, and conservation and reconstruction affect its present appearance.
roman-helmet|Nijmegen Roman cavalry helmet|Eph 6:17|Roman period|A face-mask helmet illustrates a specialized form of Roman cavalry equipment.|It is not an ordinary infantry helmet and is not an exact reconstruction of the metaphor in Ephesians.
writing-tablet|Roman wax writing tablet containing a will|Luk 1:63|c. 75–125 CE|A tablet found in Wales illustrates reusable wax-based writing.|It is not the tablet used by Zechariah and comes from another region.
reed-pen|Egyptian scribe's palette and reed pens|3Jn 1:13|Ancient Egyptian; see object record|A writing palette and reed pens provide a material comparison for writing tools.|They are Egyptian objects, not instruments used by the author of 3 John.
lmlk-jar|LMLK-stamped jar handle from Lachish|2Ki 18|Late 8th century BCE|A stamped storage-jar handle preserves an administrative mark associated with Judah.|The stamp does not identify the contents of a particular biblical storehouse.
arch-titus-menorah|Menorah relief on the Arch of Titus|Luk 21|Late 1st century CE|A Roman relief represents spoils carried after the destruction of Jerusalem's Temple.|This is a later Roman victory monument, not a photograph of the Temple's original furnishings.
nimrud-ivory|Carved ivory bedhead from Nimrud|Amo 6:4|9th–8th centuries BCE|Luxury ivory carving provides context for the imagery of elite furnishings.|It is not an ivory bed owned by one of the people addressed by Amos.
phoenician-ivory|Phoenician carved ivory|1Ki 22:39|c. 800–710 BCE|A surviving ivory carving illustrates a luxury material used around the ancient Mediterranean.|It is not an identified part of Ahab's house.
persian-seal|Achaemenid chalcedony stamp seal|Est 8:8|Achaemenid period|A seal engraved with royal-hero imagery offers a comparison for sealing documents.|It is not Esther's or the king's actual signet ring.
babylon-seal|Old Babylonian cylinder seal|Dan 6:17|Old Babylonian period|A carved seal illustrates an earlier Mesopotamian method of making an identifying impression.|It predates Daniel's setting and is not a seal used on the lions' den.
egyptian-brick|Egyptian mud brick with an administrative seal|Exo 5|12th Dynasty|A mud brick from Lahun provides a physical comparison for Egyptian building material.|It is not identified as a brick made by Israelite laborers.
fishing-weight|Egyptian fishing-net weight|Mat 4:18|c. 1295–1070 BCE|A net weight illustrates one component of fishing equipment.|It is Egyptian and much earlier than the disciples; it is not a first-century Galilean fishing object.
millstone|Roman quern fragment from Aquincum|Mat 18:6|1st–3rd centuries CE|A rotary grinding-stone fragment illustrates the material equipment of grain processing.|It is a modest quern fragment, not necessarily the large millstone envisioned in the passage.
jerusalem-ossuary|Jerusalem limestone ossuary|Jhn 19:41|Early Roman period|A museum bone box provides context for one form of burial practice around Jerusalem.|An ossuary is not the same thing as the tomb described in John, nor is this Jesus' burial container.
sarcophagus-jonah|Early Christian Jonah sarcophagus|Jon 2|Late 3rd century CE|Carved Jonah scenes show how later Christians used the narrative in funerary art.|This is later sacred sculpture, not an artifact from the lifetime or voyage of Jonah.
silver-trumpets|Silver trumpet from Tutankhamun's tomb|Num 10|c. 1336–1326 BCE|A surviving silver trumpet offers a comparison for ancient metal wind instruments.|It is Egyptian and is not one of the trumpets commanded in Numbers.
beersheba-horned|Reassembled horned altar from Beersheba|Amo 3:14|Iron Age|Reassembled stone blocks illustrate the form of an ancient horned altar.|It is from Beersheba, not the Bethel altar named in Amos; its museum appearance includes reconstruction.
jehoiachin|Babylonian ration tablet naming Jehoiachin|2Ki 25:27|6th century BCE|A ration record names the exiled king of Judah and supplies administrative context for his presence in Babylonia.|It does not narrate the release event described in 2 Kings.
nebuchadnezzar-brick|Inscribed brick fragment of Nebuchadnezzar II|Dan 4|604–562 BCE|A royal building inscription illustrates the relationship between kingship and monumental construction.|This brick is not a record of Nebuchadnezzar's dream or its interpretation.
esarhaddon|Victory stele of Esarhaddon|Isa 37:38|7th century BCE|An Assyrian royal stele supplies a material context for a ruler named in Isaiah.|The monument's victory imagery is not a depiction of the biblical scene.
artaxerxes|Achaemenid lobed bowl with royal inscription|Neh 2|c. 465–424 BCE|An inscribed royal vessel gives a comparison for Achaemenid court material culture.|It is a bowl, not a stone decree, and cannot be identified as a vessel served by Nehemiah.
sistrum|Sistrum of the chantress Tapenu|Exo 15:20|c. 1186–600 BCE|An Egyptian ritual rattle illustrates one form of ancient music-making.|A sistrum is not a tambourine and is not the instrument carried by Miriam.
roman-inkwell|Roman terracotta inkwell|2Jn 1:12|First half of the 1st century CE|A small ink container offers a period comparison for writing with ink.|It is not an object used by the author of 2 John.
roman-key|Roman bronze key with figurative handle|Rev 3:7|1st–2nd century CE|A bronze key provides a concrete comparison for the language of access and authority.|It is not the key of David; Revelation's image is symbolic.
egypt-basket|Basket and lid associated with Merytamun|Exo 2:3|c. 1525–1504 BCE|A preserved Egyptian basket shows the workmanship of woven containers.|It is not the basket that held Moses, and its form should not be treated as an exact reconstruction.
roman-strigil|Roman bronze strigil|1Co 9:24|1st–2nd century CE|A body-scraping tool offers context for ancient athletic and bathing practices.|It is not a racing implement or a prize, and the passage does not name this object.
roman-fibula|Etruscan silver boat-shaped fibula|Jas 2|7th–6th century BCE|An ancient garment fastener offers a comparison for dress and ornament.|This is Etruscan, not Roman, and many centuries earlier than James.
greek-olpe|Corinthian decorated ceramic jug|2Co 4:7|c. 630–610 BCE|A clay jug gives physical form to the metaphor of fragile earthen vessels.|It is an earlier Greek object, not a vessel owned by Paul or the Corinthian church.
silver-scrolls|Ketef Hinnom silver amulets|Num 6:24|Late 7th–early 6th century BCE|Small inscribed silver amulets preserve wording related to the priestly blessing.|They are fragmentary amulets, not complete Bible scrolls; readings require scholarly reconstruction.
ptolemy-sistrum|Sistrum associated with Ptolemy I|Exo 15:20|305–282 BCE|A Ptolemaic Egyptian rattle provides a later comparison for ritual instruments.|It is centuries later than the Exodus setting and is not Miriam's tambourine.
amasis-sistrum|Sistrum from the reign of Amasis|Exo 15:20|570–526 BCE|An Egyptian sistrum preserves decorated ritual music-making equipment.|This is a different period and instrument from the one named in Exodus.
middle-kingdom-basket|Middle Kingdom Egyptian basket and lid|Exo 2:3|c. 1981–1640 BCE|A woven basket and lid illustrate another surviving Egyptian container.|It is a separate museum object, not another view of Merytamun's basket or an identified biblical artifact.
attic-jug|Attic ceramic jug|2Co 4:7|c. 460–440 BCE|A Greek clay jug offers another comparison for earthen vessels.|It is a distinct earlier object, not a container from a known Christian household.
`;
export const OBJECT_REVIEW = Object.fromEntries(rows.trim().split('\n').map(line => {
 const [id,title,reference,date,description,caution]=line.split('|');
 return [`artifacts-${id}`,{title,reference,date,description,caution,creator:'Maker unidentified',relationship:'cultural-context',technique:'photograph',medium:'Photograph of a historical object',culture:'Ancient material culture; see object record',passageNote:description+' '+caution}];
}));
OBJECT_REVIEW['artifacts-sarcophagus-jonah']={...OBJECT_REVIEW['artifacts-sarcophagus-jonah'],kind:'artwork',collections:['heritage'],technique:'sculpture',relationship:'thematic',period:'Early Christian',medium:'Carved stone sarcophagus, photographed'};
