import { LegalPageLayout } from "@/components/legal/LegalPageLayout";
import { APP_NAME } from "@/lib/appBrand";

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service">
      <p><strong>Last updated:</strong> June 2026</p>
      <p>
        By using {APP_NAME} during the private beta, you agree to these terms. If you do not agree, please do not use the service.
      </p>

      <h2>Beta disclaimer</h2>
      <p>
        {APP_NAME} is an early beta provided &quot;as is.&quot; Features may change, break, or be removed without notice.
        We appreciate your feedback as we improve the product.
      </p>

      <h2>Your content</h2>
      <p>
        You retain ownership of content you create (journals, beliefs, notes, etc.). You grant us a limited license
        to store, process, and display your content solely to operate the service — including sending excerpts to AI
        providers when you use AI features.
      </p>

      <h2>AI features</h2>
      <p>
        AI responses are generated by third-party models and may be inaccurate or incomplete. They are for personal
        reflection and study — not professional pastoral, medical, legal, or psychological advice. Use discernment
        and consult qualified people when making important decisions.
      </p>

      <h2>Acceptable use</h2>
      <p>
        Do not abuse the service, attempt to access other users&apos; data, scrape or automate expensive AI endpoints,
        or use the app for unlawful purposes.
      </p>

      <h2>Availability</h2>
      <p>
        We may suspend or terminate beta access at any time. We are not liable for data loss during beta —
        please export important journal entries periodically.
      </p>

      <h2>Contact</h2>
      <p>
        Questions:{" "}
        <a href="mailto:support@beliefarchitecture.app">support@beliefarchitecture.app</a>
      </p>
    </LegalPageLayout>
  );
}
