/** Quiet, reading-first Morning Formula surfaces. */
export const lh = {
  title: "font-display text-foreground",
  titleLg: "text-[28px] font-bold tracking-tight text-foreground leading-tight",
  titleMd: "text-[22px] font-bold tracking-tight text-foreground leading-tight",
  titleXl: "text-xl font-semibold tracking-tight text-foreground",
  heading: "text-[15px] font-medium text-foreground",
  body: "text-[16px] text-muted-foreground leading-relaxed",
  bodySm: "text-[14px] text-muted-foreground leading-relaxed",
  bodyLg: "text-[16px] text-foreground/90 leading-relaxed",
  bodyQuote: "font-serif text-[20px] text-foreground leading-[1.8]",
  muted: "text-muted-foreground",
  faint: "text-muted-foreground/70",
  label: "text-[13px] text-muted-foreground",
  labelUpper: "text-[11px] font-medium uppercase tracking-wider text-muted-foreground",
  footnote: "text-[13px] text-muted-foreground",
  accent: "text-amber-600 dark:text-amber-500",
  accentMuted: "text-amber-600/90 dark:text-amber-500/90",
  accentLink: "text-primary hover:text-primary/80",
  icon: "text-muted-foreground",
  spinner: "text-muted-foreground",
  card: "rounded-xl border border-border/60 bg-card shadow-sm shadow-black/[0.02]",
  cardAmber: "rounded-2xl border border-border/50 bg-card",
  cardFlat: "rounded-2xl border border-border/40 bg-card",
  row: "flex items-center justify-between gap-3 px-4 py-3 min-h-[44px] w-full text-left transition-colors active:bg-muted/60 hover:bg-muted/40",
  quote: "rounded-2xl border border-border/40 bg-card p-4 text-[16px] text-muted-foreground leading-relaxed italic",
  visionBanner: "rounded-xl border border-border/60 bg-muted/25 px-4 py-3",
  input: "min-h-11 text-base bg-background border-border/60 text-foreground placeholder:text-muted-foreground rounded-[10px]",
  textarea: "min-h-11 text-base bg-background border-border/60 text-foreground placeholder:text-muted-foreground resize-none rounded-[10px]",
  btnPrimary: "w-full rounded-[12px] h-12 font-semibold text-[15px] bg-foreground text-background hover:bg-foreground/90 shadow-none",
  btnSecondary: "rounded-[12px] bg-secondary text-secondary-foreground hover:bg-secondary/80 border-0",
  btnGhost: "text-muted-foreground hover:text-foreground hover:bg-muted/60 rounded-full",
  btnDone: "w-full rounded-[12px] h-12 bg-secondary text-secondary-foreground hover:bg-secondary/80 font-medium",
  btnReviewed: "bg-muted text-muted-foreground hover:bg-muted/80",
  progress: "h-[3px] rounded-full bg-muted mb-6 overflow-hidden",
  progressFill: "h-full bg-foreground/60 rounded-full",
  pillActive: "rounded-full px-2.5 py-0.5 text-[11px] font-semibold bg-amber-500/15 text-amber-700 dark:text-amber-400",
  pillInactive: "rounded-full px-2.5 py-0.5 text-[11px] font-medium bg-muted text-muted-foreground",
  iconBox: "flex h-10 w-10 shrink-0 items-center justify-center rounded-[10px] bg-amber-500/10",
  iconBoxLg: "w-14 h-14 rounded-full bg-amber-500/15 flex items-center justify-center mb-4",
  heroCard:
    "w-full text-left rounded-3xl border border-border/50 bg-card p-6 sm:p-8",
  divider: "border-t border-border/60",
  dashedAdd:
    "w-full rounded-xl border border-dashed border-border py-2.5 text-[13px] text-muted-foreground hover:border-primary/30 hover:text-foreground transition",
  addLink: "flex items-center gap-1.5 text-[13px] text-primary py-1",
  headerAction: "text-primary hover:text-primary/80 hover:bg-muted/60 text-[13px] font-medium h-8 px-2 rounded-lg",
} as const;
