/** Sample habits from the user's Google Sheet — optional import only. */
export const DEFAULT_HABIT_NAMES: { name: string; category?: string }[] = [
  { name: "Wake up at 6:00 am", category: "Morning" },
  { name: "Unload Dishwasher", category: "Morning" },
  { name: "Check in with the Holy Spirit: Show me my day", category: "Spiritual" },
  { name: "The Bible Recap: Bible in 365 days", category: "Spiritual" },
  { name: "Shower to start the day", category: "Morning" },
  { name: "Brush Teeth", category: "Morning" },
  { name: "Make Bed", category: "Morning" },
  { name: "Make 80oz water bottle for the day", category: "Health" },
  { name: "Recite 3 things wife did great the day before", category: "Family" },
  { name: "Update Weeks Chart", category: "Life" },
  { name: "Accounting with Monarch", category: "Life" },
  { name: "Eat Breakfast", category: "Health" },
  { name: "Take Morning Vitamin Pack", category: "Health" },
  { name: "Eat Lunch", category: "Health" },
  { name: "Close the lever in your head for family", category: "Family" },
  { name: "Did you finish your 80oz water bottle?", category: "Health" },
  { name: "Workout", category: "Health" },
  { name: "Daily walk indoor or outdoors", category: "Health" },
  { name: "Nightly Brush Teeth", category: "Evening" },
  { name: "Nightly Floss Teeth", category: "Evening" },
  { name: "Skin Care Routine", category: "Evening" },
  { name: "Pray / Devotional with wife", category: "Evening" },
  { name: "Hit Golf Balls", category: "Evening" },
  { name: "Sitting in bed by 10:30", category: "Evening" },
  { name: "Water for bedside and take night vitamins", category: "Evening" },
  { name: "Balance of Nature", category: "Health" },
  { name: "Did you complete the day without cussing?", category: "Character" },
  { name: "Pray over daughter at reading time", category: "Family" },
  { name: "Add 1 Training to Training Course", category: "Growth" },
  { name: "Check Nails", category: "Evening" },
  { name: "Charge Apple Watch", category: "Evening" },
  { name: "Evening Vitamin Pack", category: "Evening" },
  { name: "Lotion", category: "Evening" },
  { name: "15 min Unobstructed Time with Wife", category: "Family" },
];
