/**
 * Lilly's permanent family cast (supporting characters).
 *
 * These are recurring "actors" who appear alongside Lilly across contemporary
 * Lilly Storybooks stories: Mama Tish, Daddy Andrew, and Winston the Airedale
 * Terrier. Unlike heroines (`characterBibles.ts`), they are not castable book
 * leads — they are a fixed family whose identity must never change.
 *
 * Each entry is a text character bible (identity anchor) plus the approved
 * reference-asset id + version (authoritative likeness from
 * `characterReferenceAssets.ts`). `modelSheetPath` is where a dedicated
 * per-character master sheet would be generated by the model-sheet script.
 */

import type { StorybookCharacterId } from "@/lib/children-books/characterReferenceAssets";

export type FamilyCharacterId = "tish" | "andrew" | "winston";

export type FamilyCharacterKind = "adult" | "animal";

export type FamilyCharacter = {
  id: FamilyCharacterId;
  name: string;
  role: string;
  kind: FamilyCharacterKind;
  /** Full character-bible prompt text (identity anchor). */
  sheet: string;
  /** Where the model-sheet script writes this character's master sheet. */
  modelSheetPath: string;
  /** Approved reference-asset id (authoritative likeness). */
  referenceAssetId: StorybookCharacterId;
  /** Approved reference-asset version required for this character. */
  referenceVersion: string;
};

export const FAMILY_CHARACTERS: Record<FamilyCharacterId, FamilyCharacter> = {
  tish: {
    id: "tish",
    name: "Tish",
    role: "Mama",
    kind: "adult",
    modelSheetPath: "children-books/character-bibles/tish/model-sheet.png",
    referenceAssetId: "tish",
    referenceVersion: "v1",
    sheet: `CHARACTER BIBLE: TISH — "MAMA" (permanent locked identity — match the approved Tish reference on every scene where she appears)

Role: Lilly's adult mother. Warm, graceful, joyful, and strong. Never a generic blonde princess; never younger-looking than Lilly's mother. Face is fixed regardless of wardrobe.

Body & proportions:
• Adult woman with natural, graceful proportions; elegant, approachable, motherly posture — never fashion-model exaggerated

Face (follow the approved reference):
• Refined soft oval face with a gentle, elegant jawline and natural cheeks
• Bright, warm, genuine, recognizable smile with simplified natural teeth
• Almond, light eyes with visible eyelids
• Soft natural eyebrows; small natural nose with a visible bridge
• Fair skin with a soft light blush — never plastic, never orange

Hair reference:
• Long, pale golden-blonde hair in soft natural waves past the shoulders; soft center-to-side part; painted as large flowing shapes — no individual strands

Silhouette & posture:
• Graceful, upright, motherly silhouette — recognizable by long blonde waves
• Signature gestures: holding Lilly's hand, an arm around the family, hands folded in prayer

Color palette (character): porcelain white, sky blue, blush pink, soft coral accents; golden-blonde hair + light eyes + fair skin.

Wardrobe (identity fixed across looks): soft pastel day dress; modest sky-blue or ivory church dress; light linen garden dress with a simple apron; soft cardigan at home. Story clothing may become modest cottage, church, royal, or contemporary while identity remains fixed.

Personality & expressions: warm, graceful, kind, strong. Preserve: joyful smile, tender warmth, gentle concern, peaceful prayer, proud delight.`,
  },

  andrew: {
    id: "andrew",
    name: "Andrew",
    role: "Daddy",
    kind: "adult",
    modelSheetPath: "children-books/character-bibles/andrew/model-sheet.png",
    referenceAssetId: "andrew",
    referenceVersion: "v1",
    sheet: `CHARACTER BIBLE: ANDREW — "DADDY" (permanent locked identity — match the approved Andrew reference on every scene where he appears)

Role: Lilly's adult father. Kind, protective, faithful, strong but gentle. Never a generic handsome prince. Face is fixed regardless of wardrobe.

Body & proportions:
• Adult man with natural, athletic proportions; relaxed, confident, protective but gentle bearing

Face (follow the approved reference):
• Natural masculine oval face with a defined but soft jawline
• Clean-shaven, or only extremely light natural facial shadow based on the approved reference — no full beard
• Friendly, warm, recognizable smile with simplified natural teeth
• Kind almond eyes with visible eyelids
• Recognizable eyebrows; straight natural nose with a visible bridge
• Warm skin with a soft natural tone — never plastic, never orange

Hair reference:
• Short, neat dark brown hair with a natural side sweep; painted as large shapes — no individual strands; no curly hair

Silhouette & posture:
• Broad-shouldered, dependable, fatherly silhouette
• Signature gestures: holding Lilly, a hand on her shoulder, kneeling to a child's height, hands folded in prayer

Color palette (character): lavender / powder-blue gingham, warm taupe and khaki, ivory; dark brown hair + warm eyes + warm skin.

Wardrobe (identity fixed across looks): light gingham button shirt with chinos; soft blazer over a collared shirt for church; rolled-sleeve outdoor shirt; simple sweater at home. Clothing may change while identity remains fixed.

Personality & expressions: kind, protective, faithful, strong. Preserve: warm smile, steady reassurance, playful fun, thoughtful concern, peaceful prayer.`,
  },

  winston: {
    id: "winston",
    name: "Winston",
    role: "the Airedale Terrier",
    kind: "animal",
    modelSheetPath: "children-books/character-bibles/winston/model-sheet.png",
    referenceAssetId: "winston",
    referenceVersion: "v1",
    sheet: `CHARACTER BIBLE: WINSTON — THE AIREDALE TERRIER (permanent locked identity — match the approved Winston reference on every scene where he appears)

Role: the family dog. Loyal, gentle, fun, and protective. Instantly recognizable. Never a generic doodle, never a golden retriever, never a small terrier puppy.

Breed & proportions:
• Adult Airedale Terrier with natural, believable dog proportions — never cartoonish, chibi, or humanized
• Athletic medium-large build; rectangular terrier muzzle; folded V-shaped ears; alert upright tail

Markings (maintain exactly):
• A black saddle over the back and upper sides
• Warm tan legs, face, and beard
• A distinctive wiry beard and eyebrows; expressive dark eyes
• Coat painted as large wiry shapes — no individual strands or fluffy AI fur

Silhouette & posture:
• Recognizable bearded-terrier silhouette with the black saddle and tan legs
• Playful, protective body language; usually near Lilly

Accessory: a soft light-blue collar or bow tie (optional and tasteful).

Color palette (character): warm tan, black saddle, with a light-blue accent.

Personality & poses: loyal, gentle, fun, protective. Preserve poses: sitting, standing, play bow, walking, running beside Lilly, and resting at her feet.`,
  },
};

export function getFamilyCharacter(id?: FamilyCharacterId | string): FamilyCharacter | undefined {
  if (id && id in FAMILY_CHARACTERS) {
    return FAMILY_CHARACTERS[id as FamilyCharacterId];
  }
  return undefined;
}

export const FAMILY_CHARACTER_IDS = Object.keys(FAMILY_CHARACTERS) as FamilyCharacterId[];
