-- Deprecated duplicate-version migration retained for history only.
-- Production journal encryption schema is reconciled by:
--   20260904190000_journal_stability_repair.sql
--
-- This file previously shared the exact same migration version as
-- 20260620120000_questions_for_god.sql, which caused migration drift.
-- Do not apply this file directly.
