-- Deprecated standalone private-notebook migration retained for history.
-- Production E2E/private notebook schema is reconciled by:
--   20260904190000_journal_stability_repair.sql
--
-- Keeping this file as a no-op prevents a fresh migration run from reintroducing
-- a source_kind constraint that omits the Notes notebook.
